db.users.insert([
	{
		name:"vinay",
		mobileNumber:9177167767,
		address:"Kurnool",
		city:"Kurnool",
		state:"Andhra Pradesh",
		country:"India"
	},
	{
		name:"vijay",
		mobileNumber:7207651251,
		address:"One Town",
		city:"Kurnool",
		state:"Andhra Pradesh",
		country:"India"
	},
	{
		name:"lucky",
		mobileNumber:9581275401,
		address:"Nandyal",
		city:"Kurnool",
		state:"Andhra Pradesh",
		country:"India"
	},
	{
		name:"Rakesh",
		mobileNumber:8073242121,
		address:"Gadwal",
		city:"Gadwal",
		state:"Telangana",
		country:"India"
	},
	{
		name:"Harsha",
		mobileNumber:9848022338,
		address:"Nellore",
		city:"Nellore",
		state:"Andhra Pradesh",
		country:"India"
	},
	{
		name:"Pavan",
		mobileNumber:9998882233,
		address:"Amritsar",
		city:"Amritsar",
		state:"Punjab",
		country:"India"
	},
	{
		name:"Rajesh",
		mobileNumber:8121546821,
		address:"Garibdar",
		city:"Mumbai",
		state:"Maharastra",
		country:"India"
	},
	{
		name:"venki",
		mobileNumber:8500652432,
		address:"Sydney",
		city:"Sydney",
		state:"Sydney",
		country:"Australia"
	},
	{
		name:"raju",
		mobileNumber:6300487767,
		address:"Kurnool",
		city:"Kurnool",
		state:"Andhra Pradesh",
		country:"India"
	},
	{
		name:"Swetha",
		mobileNumber:8883332244,
		address:"Gachibowli",
		city:"Hyderabad",
		state:"Telangana",
		country:"India"
	},
	{
		name:"Tahir Farhan",
		mobileNumber:8121345678,
		address:"Germany",
		city:"Germany",
		state:"Germany",
		country:"Germany"
	}
])